sudo: required
language: c++
services:
  - docker

before_install:
  - docker pull trusch/susi-builder:stable
  - docker pull trusch/susi-arm-builder:stable

script:
  - docker run -v $(pwd):/src trusch/susi-builder:stable
  - cp build/*.deb ./susi-shell-${TRAVIS_BRANCH}-linux-amd64.deb
  - docker run -v $(pwd):/opt/rootfs/src trusch/susi-arm-builder:stable
  - cp build/*.deb ./susi-shell-${TRAVIS_BRANCH}-linux-armhf.deb

deploy:
  provider: releases
  file:
    - "susi-shell-${TRAVIS_BRANCH}-linux-amd64.deb"
    - "susi-shell-${TRAVIS_BRANCH}-linux-armhf.deb"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: FSrdJZGMm28d58rL+6amYV3txQ1QGjWwQi/9gpsmj0AZsZpjJ09kbdDTz4f5wuHo0r2UE9/5EPhCB9zCXs3aFulFO21hVzmVqbm1UgBqXFEvNOc653AsymrStKlns6zYBRHYINv+nbaeiwU67pX6JFLeTH+zVln5H99KVTmPjcW0Q2pDo1Rfw2HYQ72LQIg/Ji3UsSr9vGLUJdd3+SRnMXA7vCeFbb7I0D068mVEQvdJE4Abc8/L+AJRBJnmM21xErW2IAe7pgNwGBakMu7jge92Nl5OVNn9e4QSF0mBUmqbDdF/AdhshYJs0pPi7uTn6gVErgQdqKiJPQq7xlq04Jhnb0nmHAvSjosjbRrEjdVcckm9RRqKaMJtihuavr1Wx+80mZqYi1ZSKKKZaxoVwTz1IYcfXZNDqjqBLwIgvp1riQKgCQ01EdcZpLxzImQSV6j66Y8UUAi4u63fbHvyda07UdscPWeOITpHfK24qYgxzh6rz6xNkCrkG1FnreHhHK1bhrQ1e0TBX7w0deDgNlWm+TVFwj805Pp+AE8CpJp9QHKm5bLjtDXbLt3g1S6tof8ObH1ceRuF93prHuAQhxx7aTjlG7DU6pxmmsZcGjp56s1+790m89GWFOSIG+zSRTBR/YF1rnb68NhuDgkn1gLmclimQJmPeiGZDDDvk/w=
